In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [2]:
data = {'Fahrzeug': ['Auto', 'Motorrad', 'Motorrad', 'Auto', 'Auto'],  'PS': [380, 70, 124, 165,156]}
DF_obj = pd.DataFrame(data)
DF_obj

   Fahrzeug   PS
0      Auto  380
1  Motorrad   70
2  Motorrad  124
3      Auto  165
4      Auto  156

In [7]:
gr=DF_obj.groupby(['Fahrzeug'])
print(gr)
# average of the group
gr.mean()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000278FB162DD0>

                  PS
Fahrzeug
Auto      233.666667
Motorrad   97.000000

In [9]:
# sum of the group
gr.sum()

           PS
Fahrzeug
Auto      701
Motorrad  194

In [10]:
# min value in the group
gr.min()

           PS
Fahrzeug
Auto      156
Motorrad   70

In [11]:
# max value in the group
gr.max()

           PS
Fahrzeug
Auto      380
Motorrad  124