In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
np.random.seed(25)
DF_obj = DataFrame(np.random.rand(36).reshape((6,6)),index=['row 1','row 2','row 3','row 4','row 5','row 6'],
                  columns=['column 1','column 2','column 3','column 4','column 5','column 6'])
DF_obj

       column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819

In [7]:
DF_obj.loc[['row 1','row 4'],['column 2','column 6']]

       column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541

In [4]:
DF_obj.loc['row 1']

column 1    0.870124
column 2    0.582277
column 3    0.278839
column 4    0.185911
column 5    0.411100
column 6    0.117376
Name: row 1, dtype: float64

In [8]:
DF_obj.loc[['row 1', 'row 4']]

       column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541