In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
missing = np.nan
series_obj = Series(['row 1', 'row 2',missing,'row 4',np.nan,np.nan,np.nan,'row 8'])
np.random.seed(25)
DF_obj = DataFrame(np.random.randn(36).reshape(6,6))
DF_obj

          0         1         2         3         4         5
0  0.228273  1.026890 -0.839585 -0.591182 -0.956888 -0.222326
1 -0.619915  1.837905 -2.053231  0.868583 -0.920734 -0.232312
2  2.152957 -1.334661  0.076380 -1.246089  1.202272 -1.049942
3  1.056610 -0.419678  2.294842 -2.594487  2.822756  0.680889
4 -1.577693 -1.976254  0.533340 -0.290870 -0.513520  1.982626
5  0.226001 -1.839905  1.607671  0.388292  0.399732  0.405477

In [3]:
DF_obj.loc[3:5, 0] = missing
DF_obj.loc[1:4, 5] = missing
DF_obj

          0         1         2         3         4         5
0  0.228273  1.026890 -0.839585 -0.591182 -0.956888 -0.222326
1 -0.619915  1.837905 -2.053231  0.868583 -0.920734       NaN
2  2.152957 -1.334661  0.076380 -1.246089  1.202272       NaN
3       NaN -0.419678  2.294842 -2.594487  2.822756       NaN
4       NaN -1.976254  0.533340 -0.290870 -0.513520       NaN
5       NaN -1.839905  1.607671  0.388292  0.399732  0.405477

In [4]:
series_obj

0    row 1
1    row 2
2      NaN
3    row 4
4      NaN
5      NaN
6      NaN
7    row 8
dtype: object

In [6]:
#series_obj.fillna(method='ffill')
series_obj.ffill()

0    row 1
1    row 2
2    row 2
3    row 4
4    row 4
5    row 4
6    row 4
7    row 8
dtype: object

In [10]:
#DF_obj.fillna(method='ffill')
DF_obj.ffill()

          0         1         2         3         4         5
0  0.228273  1.026890 -0.839585 -0.591182 -0.956888 -0.222326
1 -0.619915  1.837905 -2.053231  0.868583 -0.920734 -0.222326
2  2.152957 -1.334661  0.076380 -1.246089  1.202272 -0.222326
3  2.152957 -0.419678  2.294842 -2.594487  2.822756 -0.222326
4  2.152957 -1.976254  0.533340 -0.290870 -0.513520 -0.222326
5  2.152957 -1.839905  1.607671  0.388292  0.399732  0.405477